# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'SG PSI' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SG PSI
  pod 'Alamofire', '~> 4.4'
  pod 'ObjectMapper', '~> 2.2'
  pod 'AlamofireObjectMapper', '~> 4.0'
  pod 'GoogleMaps'

  target 'SG PSITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SG PSIUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
